# path: /etc/prometheus/prometheus.yml
# Global configuration.
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Scraping configuration.
scrape_configs:
  ## Prometheus can scrape itself to provide system statistics. Not needed, but recommended.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090', 'nodeexporter:9100']

  ## You can add multiple jobs to further stratify your farm. Job will appear as label in prometheus
  ## Just copy/paste the entire section below at the end of the file and change the name of the job
  ## and list of targets.
  - job_name: 'braiinsos-data'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    ## Use the section below in case when targets are defined statically    
    # For Braiins OS, list of targets has to include 8081 port
    - targets: ['1.2.3.4:8081','5.6.7.8:8081']
    relabel_configs:
      ###################################################################################
      # The following is an optional static label. Useful if you need to stratify your farm further.
      - target_label: "building"
        replacement: "Building A"    
      # Get rid of port in address - this will allow easy click-through from the drill-down dashboards to miner
      - source_labels: ["__address__"]
        regex: "^(.+?):.*"
        target_label: "instance"
      ###################################################################################
      # The following is optional. Useful if you manage your farm by using
      # subnets.
      # Extract the site ID (second octet of IPv4 address)
      - source_labels: ["__address__"]
        regex: "\\d+\\.(\\d+)\\.\\d+\\.\\d+.*"
        target_label: "site_id"
      # Extract the subnet ID (third octet of IPv4 address)
      - source_labels: ["__address__"]
        regex: "\\d+\\.\\d+\\.(\\d+)\\.\\d+.*"
        target_label: "subnet_id"
      # Extract the host ID (last octet of IPv4 address)
      - source_labels: ["__address__"]
        regex: "\\d+\\.\\d+\\.\\d+\\.(\\d+).*"
        target_label: "host_id"
    metric_relabel_configs:
      ###################################################################################
      # Some of the detailed metrics are better removed. You can comment out / remove
      # the following section, however doing so will greatly increase the size needed to store
      # all the data. Make sure you really need these metrics and your storage size is
      # appropriate.
      - source_labels: [ __name__ ]
        regex: 'client_generated_work|client_order|client_start_total|client_stop_total|dangerous_temperature|fan_rpm_feedback|hashboard_power|hashboard_temperature|hot_temperature|chips_discovered|chips_expected|process_cpu_seconds_total|process_max_fds|process_open_fds|process_resident_memory_bytes|process_start_time_seconds|process_threads|process_virtual_memory_bytes|stratum_job_counter|stratum_last_difficulty|stratum_request_duration_bucket|stratum_request_duration_count|stratum_request_duration_sum|tuner_iteration'
        action: drop
